### ISSUE TITLE
ctor not running for statically linked libraries

### ISSUE THREAD

**Issue by fredpointzero** [mmastrac/rust-ctor#27]
Hi,

I have an issue with the following setup:
- app crate defines the binary to produce
- lib crate defines a rust standard library

When using `#[ctor]` attribute inside the crate lib, it is not called when running the binary built with app.

Using a rust library dependency statically link it so it should also include the ctor function, but it does not seems to be the case.

Am I missing something or is this an unsupported use case?

**Comment by mmastrac** [comment]
Could you confirm which version you are using (ie: paste your Cargo.toml here)?

**Comment by fredpointzero** [comment]
I tried to have a minimal repro and investigated further, and I resulted in a behaviour I don't understand.

The repro is attached to this comment.
These are the main files:

`app/src/main.rs`
```rust
fn main() {
    println!("Main execution");
    #[cfg(feature = "assert")]
    assert_eq!(1, unsafe {
        lib::VALUE.load(std::sync::atomic::Ordering::Acquire)
    });
}
```
`app/Cargo.toml`
```toml
[package]
name = "app"
version = "0.1.0"
edition = "2018"

[dependencies]
lib = { path = "../lib" }
```

`lib/src/lib.rs`
```rust
#[macro_use]
extern crate ctor;
#[macro_use]
extern crate libc_print;

use std::sync::atomic::{AtomicUsize, Ordering};

pub static mut VALUE: AtomicUsize = AtomicUsize::new(0);

#[ctor]
fn startup() {
    unsafe {
        VALUE.fetch_add(1, Ordering::AcqRel);
    }
    libc_print!("Startup lib\r\n");
}

#[dtor]
fn tear_down() {
    libc_print!("Tear down lib\r\n");
}

fn unused() {
    let _ = unsafe { VALUE.load(Ordering::Acquire) };
}
```

`lib/Cargo.toml`
```toml
[package]
name = "lib"
version = "0.1.0"
authors = ["Frédéric Vauchelles <fredpointzero@gmail.com>"]
edition = "2018"

[dependencies]
libc-print = "0.1.8"
ctor = "0.1.10"
```

This is the strange behaviour I get:

1. `cargo run --package app --bin app` will show only `Main execution` in the console.
2. Comment the `#[cfg(feature = "assert")]` feature in the `main.rs` file
3. `cargo run --package app --bin app` will succeed

So this is weird, I can't tell if this is working when it does not access the static variable.

Also, I have my issue when using the crate `inventory` in a bigger project, but I will try to have a minimal repro in that case.

```
cargo 1.39.0-nightly (22f7dd049 2019-08-27)
rustc 1.39.0-nightly (dfd43f0fd 2019-09-01) (nightly-x86_64-pc-windows-gnu)
rustup 1.19.0 (2af131cf9 2019-09-08)

and
cargo 1.37.0 (9edd08916 2019-08-02)
rustc 1.37.0 (eae3437df 2019-08-13) (stable-x86_64-pc-windows-msvc)
rustup 1.19.0 (2af131cf9 2019-09-08)
```

[test3-rs.zip](https://github.com/mmastrac/rust-ctor/files/3597526/test3-rs.zip)
